meta_product_name: "Flare"
meta_title: "Flare - Panic Button"
meta_description: "A service that automatically connect those in need to people around Denmark who will listen to them and educate them on how to deal with the chaos happening inside their mind."
meta_image: "banner.png"
twitter_account: "@anaivanm1"


