meta_product_name: "Flare"
meta_title: "Flare - Panic Button"
meta_description: "Lorem ipsum dolor sit amet, consectetur adipisicing elit. Rem recusandae deleniti minima quia magni laudantium velit unde cumque. Amet nihil fuga deleniti illum quod! Neque?"
meta_image: "banner.png"
twitter_account: "@anaivanm1"
