meta_product_name: "Flare"
meta_title: "Flare - Send a Flare, We Are Here For You"
meta_description: "This service will automatically connect those in need to people around Denmark who will listen to them and educate them on how to deal with the chaos happening inside their mind."
meta_image: "https://i.imgur.com/sbAl3Zz.png"
twitter_account: "@anaivanm1"

